### ISSUE TITLE
Make HyperBrowser to work with Java WebView.

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/addressbook#216]
Fix incompatibility issues to make hyperbrowser to work with java webview.

**Comment by yl-coder** [comment]
Issues:

1) When WebView instance is not added into the application stage, a nullpointerexception will be thrown.
`java.lang.NullPointerException
	at com.sun.javafx.Utils.getScreen(Utils.java:686)
	at com.sun.javafx.webkit.WebPageClientImpl.getScreenBounds(WebPageClientImpl.java:105)
	at com.sun.webkit.WCWidget.fwkGetScreenRect(WCWidget.java:118)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$45(WebEngine.java:1167)
	at javafx.scene.web.WebEngine$PulseTimer$$Lambda$97/20212497.pulse(Unknown Source)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:314)
	at com.sun.javafx.tk.Toolkit$$Lambda$298/28089678.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:313)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:340)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:525)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:505)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$400(QuantumToolkit.java:334)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$43/21316499.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$39/19527015.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

Related to [this issue](https://bugs.openjdk.java.net/browse/JDK-8096204) reported in openJDK.net

However, it works fine. Just noisy stacktrace thrown by thread created internally by javafx framework.

**Comment by yl-coder** [comment]
Not appearing on the latest version of jdk. Closing this issue
