### ISSUE TITLE
A test in KeyBindingsManagerApiTest fails locally

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/addressbook#293]
The test `keyEventDetected_definedBinding_matchingEventRaised` fails locally on Mac.

**Comment by HansNewbie** [comment]
Log:
```
2016-06-24 15:59:44,247 Test worker INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/hans/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.6.4/6998922e7ac5ab307bd51c233776a67da0031298/slf4j-simple-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/hans/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.3/d90276fff414f06cb375f2057f6778cd63c6082f/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
9 [Thread-5] INFO com.tulskiy.keymaster.osx.CarbonProvider - Installing Event Handler
440 [Thread-5] INFO com.tulskiy.keymaster.osx.CarbonProvider - Registered hotkey: ctrl alt pressed X
441 [Thread-5] INFO com.tulskiy.keymaster.osx.CarbonProvider - Registered hotkey: meta alt pressed X
442 [Thread-5] INFO com.tulskiy.keymaster.osx.CarbonProvider - Registered hotkey: shift ctrl pressed X
449 [Thread-5] INFO com.tulskiy.keymaster.osx.CarbonProvider - Registered hotkey: shift meta pressed X


Wanted but not invoked:
eventManager.post(<Event intention matcher>);
-> at address.unittests.keybindings.KeyBindingsManagerApiTest.verify(KeyBindingsManagerApiTest.java:116)

However, there were other interactions with this mock:
eventManager.post(KeyBindingEvent null);
-> at address.unittests.keybindings.KeyBindingsManagerApiTest.lambda$simulateKeyEvents$2(KeyBindingsManagerApiTest.java:144)


Wanted but not invoked:
eventManager.post(<Event intention matcher>);
-> at address.unittests.keybindings.KeyBindingsManagerApiTest.verify(KeyBindingsManagerApiTest.java:116)

However, there were other interactions with this mock:
eventManager.post(KeyBindingEvent null);
-> at address.unittests.keybindings.KeyBindingsManagerApiTest.lambda$simulateKeyEvents$2(KeyBindingsManagerApiTest.java:144)


	at address.unittests.keybindings.KeyBindingsManagerApiTest.verify(KeyBindingsManagerApiTest.java:116)
	at address.unittests.keybindings.KeyBindingsManagerApiTest.verifyAccelerator(KeyBindingsManagerApiTest.java:85)
	at address.unittests.keybindings.KeyBindingsManagerApiTest.keyEventDetected_definedBinding_matchingEventRaised(KeyBindingsManagerApiTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
@m133225 you have the same problem?

**Comment by m133225** [comment]
Yes

**Comment by damithc** [comment]
Could be due to `SHORTCUT` being recognized differently on Mac. I can't do much because I can't reproduce it myself. Also check of the accelerators in question works when used manually.
