### ISSUE TITLE
NPE in model manager

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#326]
Found this in the log. Not sure how I triggered it.

```
[JavaFX Application Thread]| D 11:25:37.222           (HyperBrowser) Clearing pages which are no longer required.
[JavaFX Application Thread]| D 11:25:37.225           (HyperBrowser) Updated browser view.
[JavaFX Application Thread]| I 11:25:38.171           (EventManager) LocalModelChangedEvent: number of persons 7, number of tags 2
[JavaFX Application Thread]| I 11:25:38.171         (StorageManager) Local data changed, saving to primary data file
[pool-5-thread-1]          | I 11:25:38.201        (CloudUpdateTask) Requesting changes to the cloud. (INCOMPLETE IMPLEMENTATION)
[JavaFX Application Thread]| D 11:25:38.202           (EventManager) KeyBindingEvent: KeyBindingEvent d
[JavaFX Application Thread]| I 11:25:38.202     (KeyBindingsManager) Handling Accelerator PERSON_DELETE_ACCELERATOR D
[JavaFX Application Thread]| I 11:25:38.202           (EventManager) AcceleratorIgnoredEvent: AcceleratorIgnoredEvent PERSON_DELETE_ACCELERATOR
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at address.model.ModelManager.personHasOngoingChange(ModelManager.java:256)
	at address.model.ModelManager.deletePersonThroughUI(ModelManager.java:185)
	at address.controller.PersonOverviewController.lambda$handleDeletePersons$13(PersonOverviewController.java:127)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at address.controller.PersonOverviewController.handleDeletePersons(PersonOverviewController.java:125)
	at address.controller.PersonOverviewController.lambda$createContextMenu$20(PersonOverviewController.java:215)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$12(ControlAcceleratorSupport.java:165)
	at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:347)
	at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:163)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yl-coder** [comment]
The stacktrace matches the bug that was fixed by PR #324. Should be fixed.
