### ISSUE TITLE
TagList causing problems in Mac headless mode testing

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#360]
As noted in #314, pushing/typing `KeyCode.ESCAPE` fails to close it.
Therefore, in the full system test, the launching/testing of TagList is put to the end as a workaround, but when the app terminates, it still throws an exception (even though the test itself passes).
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1146)
	at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
	at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
	at javafx.application.Platform.isSupported(Platform.java:168)
	at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
	at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
	at javafx.scene.Node.impl_intersects(Node.java:4943)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2942)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
	at javafx.scene.Node.impl_pickNode(Node.java:4912)
	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3899)
	at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3485)
	at javafx.scene.Scene.pick(Scene.java:1942)
	at javafx.scene.Scene.access$6700(Scene.java:159)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3799)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.monocle.MonocleView.notifyMouse(MonocleView.java:118)
	at com.sun.glass.ui.monocle.input.MouseInput.notifyMouse(MouseInput.java:309)
	at com.sun.glass.ui.monocle.input.MouseInput.lambda$postMouseEvent$22(MouseInput.java:222)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
	at com.sun.glass.ui.monocle.RunnableProcessor.enterNestedEventLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.MonocleApplication._enterNestedEventLoop(MonocleApplication.java:148)
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583)
	at javafx.stage.Stage.showAndWait(Stage.java:474)
	at address.controller.MainController.showTagList(MainController.java:425)
	at address.controller.RootLayoutController.handleShowTags(RootLayoutController.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
```

**Comment by damithc** [comment]
The ESC key works in other places, so there is another compounding factor causing this that we are yet to discover.

**Comment by m133225** [comment]
Actually, this seems to happen (at least now) even in headful mode when other tests are run before it. Could be the same problem as `TagEditDialog`, where the focus isn't on the dialog itself unless we manually click it (`TagListDialog` does not even request for focus, so probably that caused the failure in headful!)

**Comment by m133225** [comment]
Also, when running `MainApp` after running some(?) tests, the `TagListDialog` seems to ignore the first `ESCAPE` keypress.
