### ISSUE TITLE
Updater errors during full test run

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#375]
Updater seems to be running during the full test run. There are some updater-related exceptions in the console during the test run.

**Comment by damithc** [comment]
@HansNewbie have a look at this?

**Comment by HansNewbie** [comment]
Yes it will run. The only way to turn it off is to read if it is running from JAR or not, and only run the updater if running from JAR. Will take a look at it.

**Comment by damithc** [comment]
It is fine, even preferred to have it running during full system tests, as
long as it doesn't cause problems like extra stack traces.

-- 
Sent from a mobile device.

**Comment by HansNewbie** [comment]
Noted. Will look at it.

**Comment by damithc** [comment]
Here are the errors I see during full test run (Windows, IDEA) with coverage.
```
[m	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_73]
[m	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_73]
[m	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_73]
[m	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:1.8.0_73]
[m	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_73]
[m	at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_73]
[m	at java.nio.file.Files.copy(Files.java:3016) ~[?:1.8.0_73]
[m	at address.updater.UpdateManager.downloadFile(UpdateManager.java:274) ~[main/:?]
[m	at address.updater.UpdateManager.downloadAllFilesToBeUpdated(UpdateManager.java:257) ~[main/:?]
[m	at address.updater.UpdateManager.checkForUpdate(UpdateManager.java:136) ~[main/:?]
[m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
[m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
[m	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

```
Exception in thread "pool-7-thread-2" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at address.updater.UpdateManager.extractJarUpdater(UpdateManager.java:295)
	at address.updater.UpdateManager.checkForUpdate(UpdateManager.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
[mjava.io.IOException: Access is denied
[m	at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_73]
[m	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_73]
[m	at address.util.FileUtil.createFile(FileUtil.java:47) ~[main/:?]
[m	at address.updater.UpdateManager.downloadFile(UpdateManager.java:271) ~[main/:?]
[m	at address.updater.UpdateManager.downloadAllFilesToBeUpdated(UpdateManager.java:257) ~[main/:?]
[m	at address.updater.UpdateManager.checkForUpdate(UpdateManager.java:136) ~[main/:?]
[m	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
[m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
[m	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

**Comment by damithc** [comment]
All three happen even if we are no measuring coverage, so they are not triggered by coverage tools. However, some of them seem to be non-deterministic. Happens only sometimes.

**Comment by HansNewbie** [comment]
The first and third errors are Windows's Java problem. Encountered it some issues back because Windows Java can't handle certain paths properly. Will look into them.

Will also look at the second error. Seems weird but I might miss out something.

**Comment by HansNewbie** [comment]
I am sure the second error should never happen. That error message is because the resources in production cannot be found on running a test (input stream is null), but I tried on Mac and Windows that the production resources are included in test environment.

The error could be concurrency issue on the test environment but not because of the code.

**Comment by HansNewbie** [comment]
For third error, based on [this](http://stackoverflow.com/questions/12933106/java-io-ioexception-access-denied-h2-hibernate), the possibilities for the error as relevant to the updater piece of code:
1. There is a folder named exactly the same as the JAR file - unlikely due default folders would not have the name ending with `.jar`.
2. Not having the privilege to create a folder or a file in the environment - unlikely since there is no other complaints of other file being created (like `config.json`).

My guess, again, is on test environment concurrency combined with Windows privilege system; e.g. previous test has not been cleaned up but the next one already runs and on Windows you can't touch certain files while it's being used.

Will look into this error again on understanding the first error.

**Comment by damithc** [comment]
Need to prevent unrelated 'harmless' stack traces during testings. Otherwise potentially harmful stacktraces can be mistaken as harmless stacktarces.

**Comment by HansNewbie** [comment]
Just checked and the two codes has no `e.printStackTrace` calls. Not sure why they are there.
