### ISSUE TITLE
Log4j warning during testing

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#383]
Happens in travis as well as local (Windows)
Doesn't seem to affect the results though.
```
INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory

**Comment by damithc** [comment]
This error follows the one given above.
```
    2016-07-02 03:04:05,220 Test worker ERROR Could not reconfigure JMX java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/management/MBeanServer"

    	at java.lang.ClassLoader.defineClass1(Native Method)

    	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)

    	at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:250)

    	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:194)

    	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:71)

    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:328)

    	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:250)

    	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:162)

    	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:138)

    	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:502)

    	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:561)

    	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:577)

    	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:212)

    	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)

    	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)

    	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)

    	at address.util.LoggerManager.getLogger(LoggerManager.java:50)

    	at address.util.LoggerManager.getLogger(LoggerManager.java:59)

    	at address.util.LoggerManager.<clinit>(LoggerManager.java:12)

    	at address.model.ModelManager.<clinit>(ModelManager.java:31)

    	at sun.reflect.GeneratedSerializationConstructorAccessor25.newInstance(Unknown Source)

    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

    	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)

    	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)

    	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)

    	at org.powermock.api.mockito.repackaged.ClassImposterizer.createProxy(ClassImposterizer.java:144)

    	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:59)

    	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:50)

    	at org.powermock.api.mockito.repackaged.CglibMockMaker.createMock(CglibMockMaker.java:25)

    	at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:47)

    	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)

    	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)

    	at org.mockito.Mockito.mock(Mockito.java:1285)

    	at org.mockito.Mockito.mock(Mockito.java:1163)

    	at address.astorage.StorageManagerTest.setup(StorageManagerTest.java:62)

    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

    	at java.lang.reflect.Method.invoke(Method.java:498)

    	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)

    	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:300)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:288)

    	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)

    	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:147)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)

    	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)

    	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)

    	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)

    	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)

    	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)

    	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)

    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)

    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)

    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)

    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)

    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

    	at java.lang.reflect.Method.invoke(Method.java:498)

    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)

    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)

    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

    	at java.lang.reflect.Method.invoke(Method.java:498)

    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)

    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)

    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

    	at java.lang.Thread.run(Thread.java:745)

**Comment by m133225** [comment]
Don't think the INFO and ERROR messages are related.
- The INFO log message appears probably since `Loader.isClassAvailable("javax.servlet.ServletContext")` evaluates to true in log4j as seen [in its source code](https://logging.apache.org/log4j/2.0/log4j-core/apidocs/src-html/org/apache/logging/log4j/core/lookup/Interpolator.html) (line 116+).
- The ERROR log message is probably due to some conflict with PowerMock logging functionalities.

**Comment by damithc** [comment]
Yes, they may be unrelated although they seem to appear one after the other.

**Comment by m133225** [comment]
Moved the error problem to #409
