### ISSUE TITLE
TestApp causes BufferOverflowException in headless mode

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#444]
Probably the cloud console exceeding the frame buffer. This does not cause the tests to fail.
```
java.nio.BufferOverflowException
    	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:363)
    	at com.sun.javafx.tk.quantum.UploadingPainter.run(UploadingPainter.java:153)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    	at java.lang.Thread.run(Thread.java:745)
```

**Comment by damithc** [comment]
Using `git bisect` (very useful feature by the way), I've narrowed down the problem to this commit https://github.com/HubTurbo/addressbook/commit/4c1db6c0df0c3c89e8cd4825e3caa33f90714cf6
@yl-coder 
The error can be replicated by running all tests in headless mode locally.

**Comment by damithc** [comment]
Seems it doesn't cause test failure in travis or in headful mode, but it does fail in gradle headless mode.

**Comment by damithc** [comment]
Looks like this is affecting even headfull tests, making them slower and susceptible to failures due to slow reactions.

**Comment by yl-coder** [comment]
The error also came from [https://github.com/HubTurbo/addressbook/pull/414](https://github.com/HubTurbo/addressbook/pull/414). Which is two node behind 
https://github.com/HubTurbo/addressbook/commit/4c1db6c0df0c3c89e8cd4825e3caa33f90714cf6

**Comment by yl-coder** [comment]
Apparently, it came back again. will check again

**Comment by yl-coder** [comment]
False alarm :p.
