### ISSUE TITLE
Upgrader should keep retrying when trying to replace updater

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#536]
Currently update fails on Windows since it is attempting to replace the updater before it closes.

**Comment by m133225** [comment]
Seems like this is not the case:
```
Exception in thread "pool-7-thread-1" java.util.regex.PatternSyntaxException: Illegal Unicode escape sequence near index 5
lib\updater-\d\.\d\.\d\.jar
     ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.uxxxx(Unknown Source)
        at java.util.regex.Pattern.u(Unknown Source)
        at java.util.regex.Pattern.escape(Unknown Source)
        at java.util.regex.Pattern.atom(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.matches(Unknown Source)
        at java.lang.String.matches(Unknown Source)
        at updater.Updater.lambda$getUpdaterFile$13(Updater.java:167)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.HashMap$KeySpliterator.tryAdvance(Unknown Source)
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.findAny(Unknown Source)
        at updater.Updater.getUpdaterFile(Updater.java:168)
        at updater.Updater.checkForUpdate(Updater.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
